// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"attendance-record/client/model"
	"attendance-record/client/view"
	"attendance-record/shared"
	"fyne.io/fyne/v2"
)

// Injectors from wire.go:

func initTimeStatusView(w fyne.Window, r *model.TimeStatusReceiver) *view.TimeStatusView {
	timeStatusView := view.NewTimeStatusView(w, r)
	return timeStatusView
}

func initTimeStatusReceiver(a *shared.App) *model.TimeStatusReceiver {
	api := model.NewApi(a)
	timeStatusReceiver := model.NewTimeStatusReceiver(api)
	return timeStatusReceiver
}
