// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package client

import (
	"attendance-record/client/model"
	"attendance-record/client/view"
	"attendance-record/shared"
	"fyne.io/fyne/v2"
)

// Injectors from wire.go:

func initTimeStatusView(w fyne.Window, a *shared.App) *view.TimeStatusView {
	api := model.NewApi(a)
	timeStatusReceiver := model.NewTimeStatusReceiverSingleton(api)
	timeStatusView := view.NewTimeStatusView(w, timeStatusReceiver)
	return timeStatusView
}
